name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: newpassword
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
        working-directory: /Users/lizlubelczyk/Documents/Sirius/twitter-backend/node/express-prisma-typescript

      - name: Run tests
        env:
          DATABASE_URL: postgresql://test_user:pass123@localhost:5432/emil-service
        run: yyarn --cwd /Users/lizlubelczyk/Documents/Sirius/twitter-backend/node/express-prisma-typescript jest
